chooseright/urls.py
"""chooseright URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views
from users import views as users_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('account/', include('users.urls', namespace='users')),
    path('tellme/', include("tellme.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

core/urls.py
from django.urls import path
from django.urls import reverse
from . import views as core_views

app_name = 'core'

urlpatterns = [
	path('base', core_views.base_view, name='base'),
	path('', core_views.home_view, name='home'),
	path('search/', core_views.search_view, name='search'),
	path('catagory/<slug:slug_text>/', core_views.catagory_view, name='catagory'),
	path('brand/<slug:slug_text>/', core_views.brand_view, name='brand'),
	path('compare/', core_views.compare_view, name='compare'),
	path('add_wishlist/<int:wished_product>/', core_views.add_to_wishlist, name='add_wishlist'),
	path('about/', core_views.about_view, name='about'),
	path('privacy_policy/', core_views.privacy_policy_view, name='privacy_policy'),
	path('terms_of_use/', core_views.terms_of_use_view, name='terms_of_use'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import reverse
from . import views as user_view

app_name = 'users'

urlpatterns = [

    path('register/', user_view.register_view, name="register"),

    path('login/',
    	user_view.LoginView.as_view(redirect_authenticated_user = True),
    	name='login'),

    path('logout/', user_view.logout_view, name="logout"),

    path('password_reset/',
    	user_view.PasswordResetView.as_view(),
    	name='password_reset'),

    path('password_reset/done/',
    	user_view.PasswordResetDoneView.as_view(),
    	name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>',
    	user_view.PasswordResetConfirmView.as_view(),
    	name='password_reset_confirm'),

    path('password_reset_complete/',
    	user_view.PasswordResetCompleteView.as_view(),
    	name='password_reset_complete'),

    path('dash_board/', user_view.dash_board_view, name="dash_board"),
    path('wish_list/', user_view.wish_list_view, name="wish_list"),
    path('feedback/', user_view.feedback_view, name="feedback"),
    path('change_password/', user_view.change_password_view, name="change_password"),
    path('profile_update/', user_view.profile_view, name="profile"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
import datetime
from PIL import Image


Gender_Option = (
    ('M','Male'),
    ('F','Female'),
    )

#Custom model to make sure that that email feild is unique for each user
class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)

    def __str__(self):
        return self.username



class Profile(models.Model):
    table_name = get_user_model()
    user = models.OneToOneField(table_name, on_delete=models.CASCADE)
    image = models.ImageField(
        default = 'profile_pics/default.jpg',
        upload_to = 'profile_pics'
        )
    birth_date = models.DateField(
        blank = True,
        verbose_name = 'Date of Birth',
        null=True
        )
    gender = models.CharField(
        blank = True,
        choices = Gender_Option,
        max_length = 1, default = '',
        verbose_name = 'Gender',
        null=True
        )
    city = models.CharField(
        blank = True,
        null = True,
        max_length = 50,
        default = '',
        verbose_name = 'City'
        )

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        try:
            this = Profile.objects.get(id=self.id)
            if this.image != self.image:
                if this.image != 'profile_pics/default.jpg':
                    this.image.delete(save=False)

        except: pass
        super(Profile, self).save( *args, **kwargs )

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from .models import Profile


YEARS= [x for x in range(1980,2021)]
Gender_Option = (
    ('M','Male'),
    ('F','Female'),
    )


class UserRegisterForm(UserCreationForm):
	username = forms.CharField(
		label='Username',
		)

	first_name = forms.CharField(
		label='First Name',
		required=False,
		)

	last_name = forms.CharField(
		label='Last Name',
		max_length=100
		)

	email = forms.EmailField()

	password1 = forms.CharField(label='Password')

	password2 = forms.CharField(label='Confirm Password')

	class Meta:
		model = get_user_model()
		fields = [
		'email',
		'username',
		'first_name',
		'last_name',
		'password1',
		'password2',
		]


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email / Username')

    

class UserUpdateForm(forms.ModelForm):
	first_name = forms.CharField(
		label='First Name',
		required=False,
		max_length=100
		)

	last_name = forms.CharField(
		label='Last Name',
		required=False,
		max_length=100)

	email = forms.EmailField()

	class Meta:
		model = get_user_model()
		fields = [	
		'first_name',
		'last_name',
		'email',
		]


class ProfileUpdateForm(forms.ModelForm):
	birth_date= forms.DateField(
		label='Date of Birth',
		required=False,
		widget=forms.SelectDateWidget(years=YEARS,))

	city = forms.CharField(
		label='City',
		required=False,
		)

	gender = forms.ChoiceField(
		choices = Gender_Option,
		required=False,
		widget=forms.RadioSelect())

	class Meta:
		model = Profile
		fields =[
		'birth_date',
		'city',
		'gender',
		'image',
		]

users/views.py
from django.shortcuts import (render,
	redirect,
	get_object_or_404,
	HttpResponseRedirect
	)

from .forms import (
	UserRegisterForm,
	UserUpdateForm,
	ProfileUpdateForm,
	LoginForm
	)

from django.contrib import messages
from django.conf import settings

from django.contrib.auth.models import User
from django.contrib.auth.forms import (
	PasswordChangeForm,
	PasswordResetForm,
	SetPasswordForm,
	)
from django.contrib.auth import (
	update_session_auth_hash,
	logout
	)
from django.contrib.auth.decorators import (
	login_required,
	user_passes_test
	)
from core.models import (
	CatagoryTable,
	BrandTable,
	StoreTable,
	ProductTable,
	ProductSpecificationTable,
	Wishlist
	)
from django.core.paginator import (
	Paginator,
	EmptyPage,
	PageNotAnInteger
	)
from django.contrib.auth import views as auth_views
from tellme.models import Feedback



# Decorators to restrict user activity
def anonymous_required(function=None, redirect_url=None):

   if not redirect_url:
       redirect_url = settings.LOGIN_REDIRECT_URL

   actual_decorator = user_passes_test(
       lambda u: u.is_anonymous(),
       login_url=redirect_url
   )

   if function:
       return actual_decorator(function)
   return actual_decorator


# Views for User Module

#Verifying user is not logged-in before creating new account
def register_view(request):
	if request.user.is_authenticated:
		messages.warning(request, f'You must logout first in order to create a new account')
		return dash_board_view_access(request)
	else:
		return register_view_verified(request)


#View to handle user requests for registration
def register_view_verified(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)

		if form.is_valid():
			user = form.save()
			user.refresh_from_db()
			user.first_name = form.cleaned_data.get('first_name')
			user.last_name = form.cleaned_data.get('last_name')
			user.email = form.cleaned_data.get('email')
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account Created ! You can now log-in')
			return redirect('users:login')

	else:
		form = UserRegisterForm()

	register_view_dict = {
		'form': form,
		'title':'Create Your Account - Choose Right'
		}

	return render(request, 'users/register.html', register_view_dict)



# Class based view for log-out
class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Login - Choose Right'
        return context

# Handling log-out request
def logout_view(request):
    logout(request)
    return redirect(request.GET.get('next'))



# Class based views for password reset proccess
class PasswordResetView(auth_views.PasswordResetView):
    form_class = PasswordResetForm
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = '/account/password_reset/done/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reset Password - Choose Right'
        return context

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reset Password - Choose Right'
        return context

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
	form_class = SetPasswordForm
	template_name = 'users/password_reset_confirm.html'
	success_url = '/account/password_reset_complete/'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Reset Password - Choose Right'
		return context

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reset Password Complete - Choose Right'
        return context


# Views for User Account Options


#Dashboard view/ Users main profile view
def dash_board_view(request):
    if request.user.is_anonymous:
        messages.warning(request, f'You must log-in first to access your account page.')

    return dash_board_view_access(request)


@login_required()
def dash_board_view_access(request):
	if request.user.first_name:
		title = request.user.first_name
	else:
		title = request.user.username

	current_user = request.user
	catagory = CatagoryTable.objects.all()

	wishlist = Wishlist.objects.all().filter(user_id__exact=current_user.id).count()
	feedback = Feedback.objects.all().filter(user_id__exact=current_user.id).count()

	dash_board_view_dict = {
		'title': title+"'s" + ' Profile - Choose Right',
		'wishlist': wishlist,
		'feedback': feedback,
		'catagory': catagory
		}
	return render(request, 'users/dash-board.html',dash_board_view_dict)


#Users wishlist view
def wish_list_view(request):
    if request.user.is_anonymous:
        messages.warning(request, f'You must log-in first to access your wishlist page.')
    return wish_list_view_access(request)


@login_required()  
def wish_list_view_access(request):
	current_user = request.user
	wishlist = Wishlist.objects.all().filter(user_id__exact=current_user.id)
	catagory = CatagoryTable.objects.all()

	#Pagination 
	page = request.GET.get('page',1)
	paginator = Paginator(wishlist, 12)
	try:
		wishlist = paginator.page(page)
	except PageNotAnInteger:
		wishlist = paginator.page(1)
	except EmptyPage:
		wishlist = paginator.page(paginator.num_pages)

	wishlist_dict = {
		'title': 'Wishlist',
		'wishlist': wishlist,
		'product_pages': wishlist,
		'catagory': catagory
	}
	return render(request, 'users/wishlist.html', wishlist_dict)

#Users reviews/feedback view
def feedback_view(request):
    if request.user.is_anonymous:
        messages.warning(request, f'You must log-in first to access your review page.')
    return feedback_view_access(request)


@login_required()  
def feedback_view_access(request):
	current_user = request.user
	feedback = Feedback.objects.all().filter(user_id__exact=current_user.id)
	catagory = CatagoryTable.objects.all()

	feedback_dict = {
		'title': 'Feedback',
		'feedback': feedback,
		'catagory': catagory
	}
	return render(request, 'users/reviews.html',feedback_dict)



def profile_view(request):
    if request.user.is_anonymous:
        messages.warning(request, f'You must log-in first to view your profile.')
    return profile_view_access(request)


@login_required()  
def profile_view_access(request):
	catagory = CatagoryTable.objects.all()
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST,
								instance=request.user)
		p_form = ProfileUpdateForm(request.POST,
									request.FILES,
									instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your profile has been updated successfully.')
			return redirect('users:profile')


	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	profile_dict = {
		'title': 'Update Profile Information',
		'u_form': u_form,
		'p_form': p_form,
		'catagory': catagory
	}

	return render(request, 'users/profile.html', profile_dict)


def change_password_view(request):
    if request.user.is_anonymous:
        messages.warning(request, f'You must log-in first.')
    return change_password_view_access(request)


@login_required() 
def change_password_view_access(request):
	catagory = CatagoryTable.objects.all()
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user = request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, f'Your password has been updated successfully.')
			return redirect('users:dash_board')


	else:
		form = PasswordChangeForm(user = request.user)

	change_password_view_dic = {
		'title': 'Change Password',
		'form': form,
		'catagory': catagory
	}
	return render(request, 'users/change_password.html', change_password_view_dic)

users/templates/users/dash-board.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div id="page-content" class="no-padding no-shadow">


	<h2 class="page-title">My Account</h2>

	<div class="no-padding no-shadow profile-content">
		<div class="side-bar-menu-wrapper column-left-lg">

			<div class="widget">

				<div class="sidebar-widget">

					<h2>My Apps</h2>
					<hr>

					<ul class="widget-list">

						<li class="">
							<a class="widget-link" href="{% url 'users:wish_list' %}">
								<span>
									<i class="far fa-heart"></i>
									Wish List
								</span>
							</a>
						</li>

						<li class="">
							<a class="widget-link" href="{% url 'users:feedback' %}">
								<span>
									<i class="fas fa-feather-alt"></i>
									Feedback
								</span>
							</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="widget">

				<div class="sidebar-widget">

					<h2>Account Options</h2>
					<hr>

					<ul class="widget-list">
						<li class="">
							<a class="widget-link" href="{% url 'users:dash_board' %}">
								<span>
									<i class="fas fa-user-circle"></i>
									Dashboard
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:change_password' %}">
								<span>
									<i class="fas fa-key"></i>
									Change Password
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:profile' %}">
								<span>
									<i class="fas fa-user-cog"></i>
									Update Profile
								</span>
							</a>
						</li>
					</ul>

				</div>

			</div>

		</div>


		<div class="column-right-lg">

			<div class="dashboard-box">

				<div class="dash-box-hd">
					<h3>
						<span class="fl">
							<div class="media">
								<img class="rounded-circle account-img" src="{{user.profile.image.url }}">
								<div class="media-body">
									<h2 class="account-heading"> Welcome {{user.username}}!</h2>
									<p class="text-secondary">{{user.email}}</p>
									<span class="text-secondary">Member Since:</span> 
									<span class="text-secondary">{{ user.date_joined|date:"D, d M, Y" }}</span> 
								</div>
							</div>
						</span> 
					</h3>
				</div>

				<div class="dashboard-content">

					<ul class="account-content">
						
						<li class="account-wishlist">
							<legend class="border-bottom accout-legend">My Wishlist</legend>
							<span class="account-info">
								You have {{wishlist}} products in your wishlist.
							</span>
						</li>
						<li class="account-reviews">
							<legend class="border-bottom accout-legend">My Feedback</legend>
							<span class="account-info">
								{% if feedback == 0 %}
									You have provided feedback {{feedback}} times!
									<br>
									We value your feedback and views about our work with high regards.
								{% else %}
									You have provided feedback {{feedback}} times! Thank You.
									<br>
									We value your feedback and views about our work with high regards.
								{% endif %}
							</span>
						</li>

					</ul>

				</div>

			</div>

		</div>

	</div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends 'users/index.html' %}

{% block content %}


	<h1>You have been logged out</h1>
	<h2>Thanks for spending some quality time with the Web site today.</h2>
	<div class="border-top pt-3">
		<a href="{% url 'users:login' %}">Log In Again</a>
	</div>

{% endblock content %}

users/templates/users/password_reset_email.html
{% extends "registration/password_reset_email.html" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

users/templates/users/price_alerts.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div id="page-content" class="no-padding no-shadow">


	<h2 class="page-title">My Account</h2>

	<div class="no-padding no-shadow profile-content">
		<div class="side-bar-menu-wrapper column-left-lg">

			<div class="widget">

				<div class="sidebar-widget">

					<h2>My Apps</h2>
					<hr>

					<ul class="widget-list">

						<li class="">
							<a class="widget-link" href="{% url 'users:wish_list' %}">
								<span>
									<i class="far fa-heart"></i>
									Wish List
								</span>
							</a>
						</li>

						<li class="">
							<a class="widget-link" href="{% url 'users:feedback' %}">
								<span>
									<i class="fas fa-feather-alt"></i>
									Feedback
								</span>
							</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="widget">

				<div class="sidebar-widget">

					<h2>Account Options</h2>
					<hr>

					<ul class="widget-list">
						<li class="">
							<a class="widget-link" href="{% url 'users:dash_board' %}">
								<span>
									<i class="fas fa-user-circle"></i>
									Dashboard
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:change_password' %}">
								<span>
									<i class="fas fa-key"></i>
									Change Password
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:profile' %}">
								<span>
									<i class="fas fa-user-cog"></i>
									Update Profile
								</span>
							</a>
						</li>
					</ul>

				</div>

			</div>

		</div>


		<div class="column-right-lg">

			<div class="dashboard-box">

				<div class="account-options-header">
					<span class="account-options-tittle"> Price Alerts </span>
				</div>
				<div class="account-options-content">
					<p>No alerts to show right now</p>
				</div>
			</div>

			

		</div>

	</div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'chooseright/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div id="page-content" class="no-padding no-shadow">
	
	<h2 class="page-title">My Account</h2>

	<div class="no-padding no-shadow profile-content">
		<div class="side-bar-menu-wrapper column-left-lg">

			<div class="widget">

				<div class="sidebar-widget">

					<h2>My Apps</h2>
					<hr>

					<ul class="widget-list">

						<li class="">
							<a class="widget-link" href="{% url 'users:wish_list' %}">
								<span>
									<i class="far fa-heart"></i>
									Wish List
								</span>
							</a>
						</li>

						<li class="">
							<a class="widget-link" href="{% url 'users:feedback' %}">
								<span>
									<i class="fas fa-feather-alt"></i>
									Feedback
								</span>
							</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="widget">

				<div class="sidebar-widget">

					<h2>Account Options</h2>
					<hr>

					<ul class="widget-list">
						<li class="">
							<a class="widget-link" href="{% url 'users:dash_board' %}">
								<span>
									<i class="fas fa-user-circle"></i>
									Dashboard
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:change_password' %}">
								<span>
									<i class="fas fa-key"></i>
									Change Password
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:profile' %}">
								<span>
									<i class="fas fa-user-cog"></i>
									Update Profile
								</span>
							</a>
						</li>
					</ul>

				</div>

			</div>

		</div>


		<div class="column-right-lg">

			<div class="dashboard-box">

				<div class="dash-box-hd">
					<h3>
						<span class="fl">
							<div class="media">
								<img class="rounded-circle account-img" src="{{user.profile.image.url }}">
								<div class="media-body">
									<h2 class="account-heading"> Welcome {{user.username}}!</h2>
									<p class="text-secondary">{{user.email}}</p>
									<span class="text-secondary">Member Since:</span> 
									<span class="text-secondary">{{ user.date_joined|date:"D, d M, Y" }}</span> 
								</div>
							</div>
						</span> 
					</h3>
				</div>

			</div>

			<div class="form-content-section">
				<legend class="border-bottom mb-4">User Profile Information</legend>
				<form method="POST" class="profile-update" enctype="multipart/form-data">
					{% csrf_token %}
					<fieldset class="form-group-main">
						{{ u_form|crispy }}
						{{ p_form|crispy }}
					</fieldset>
					<div class="form-group-options">
						<button class="btn btn-outline-primary form-button" type="submit">Save</button>
					</div>
				</form>

			</div>

		</div>

	</div>
</div>

{% endblock content %}

users/templates/users/reviews.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div id="page-content" class="no-padding no-shadow">


	<h2 class="page-title">My Account</h2>

	<div class="no-padding no-shadow profile-content">
		<div class="side-bar-menu-wrapper column-left-lg">

			<div class="widget">

				<div class="sidebar-widget">

					<h2>My Apps</h2>
					<hr>

					<ul class="widget-list">

						<li class="">
							<a class="widget-link" href="{% url 'users:wish_list' %}">
								<span>
									<i class="far fa-heart"></i>
									Wish List
								</span>
							</a>
						</li>

						<li class="">
							<a class="widget-link" href="{% url 'users:feedback' %}">
								<span>
									<i class="fas fa-feather-alt"></i>
									Feedback
								</span>
							</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="widget">

				<div class="sidebar-widget">

					<h2>Account Options</h2>
					<hr>

					<ul class="widget-list">
						<li class="">
							<a class="widget-link" href="{% url 'users:dash_board' %}">
								<span>
									<i class="fas fa-user-circle"></i>
									Dashboard
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:change_password' %}">
								<span>
									<i class="fas fa-key"></i>
									Change Password
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:profile' %}">
								<span>
									<i class="fas fa-user-cog"></i>
									Update Profile
								</span>
							</a>
						</li>
					</ul>

				</div>

			</div>

		</div>


		<div class="column-right-lg">

			<div class="dashboard-box">

				<div class="account-options-header">
					<span class="account-options-tittle">My Feedbacks </span>
				</div>
				<div class="account-options-content">
					{% if feedback %}
						{% for entity in feedback %}
							<div class="feedback-row">
								<a href="{{entity.screenshot.url}}">
									<img class="feedback-img" src="{{entity.screenshot.url}}" alt="Screenshoot">
								</a>
								<div class="feedback-info">
									<legend>Feedback Information</legend>
									<span>Date Posted: {{ entity.created|date:"D, d M, Y" }}</span>
									<br>
									<span>Comment: {{entity.comment}}</span>
									<br>
									<span>Contact Email: {{entity.user.email}}</span>
								</div>
							</div>
						{% endfor %}
					{% else %}
						<p class="empty-list">Sorry! You have not provided any feedback so far.</p>
					{% endif %}
				</div>
			</div>

			

		</div>

	</div>
</div>

{% endblock content %}

users/templates/users/wishlist.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div id="page-content" class="no-padding no-shadow">


	<h2 class="page-title">My Account</h2>

	<div class="no-padding no-shadow profile-content">
		<div class="side-bar-menu-wrapper column-left-lg">

			<div class="widget">

				<div class="sidebar-widget">

					<h2>My Apps</h2>
					<hr>

					<ul class="widget-list">

						<li class="">
							<a class="widget-link" href="{% url 'users:wish_list' %}">
								<span>
									<i class="far fa-heart"></i>
									Wish List
								</span>
							</a>
						</li>

						<li class="">
							<a class="widget-link" href="{% url 'users:feedback' %}">
								<span>
									<i class="fas fa-feather-alt"></i>
									Feedback
								</span>
							</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="widget">

				<div class="sidebar-widget">

					<h2>Account Options</h2>
					<hr>

					<ul class="widget-list">
						<li class="">
							<a class="widget-link" href="{% url 'users:dash_board' %}">
								<span>
									<i class="fas fa-user-circle"></i>
									Dashboard
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:change_password' %}">
								<span>
									<i class="fas fa-key"></i>
									Change Password
								</span>
							</a>
						</li>
						<li class="">
							<a class="widget-link" href="{% url 'users:profile' %}">
								<span>
									<i class="fas fa-user-cog"></i>
									Update Profile
								</span>
							</a>
						</li>
					</ul>

				</div>

			</div>

		</div>


		<div class="column-right-lg">

			<div class="dashboard-box">

				<div class="account-options-header">
					<span class="account-options-tittle"> My Wishlist </span>
				</div>
					{% if wishlist %}
						<div class="product-row">
							{% for entity in wishlist %}
								<div class="card-container">

									<div class="card-inside">
										<img class="card-img-top" src="{{entity.wished_product.image.url}}" alt="Card image cap">
										<div class="card-body">
											<a class="card-title" href="{% url 'core:compare' %}?p_name={{entity.wished_product.product_name}}">{{entity.wished_product.product_name}}
											</a>
											<div class="card-price">
												<span class="price-sign">Rs.</span>
												<span class="price">
													{{entity.wished_product.product_price}}
												</span>
											</div>
										</div>
									</div>

									<div class="card-compare">
										<a href="{% url 'core:compare' %}?p_name={{entity.wished_product.product_name}}" class="compare-button"><span>Let's Compare</span></a>
									</div>

								</div>
							{% endfor %}
						</div>
					{% else %}
					<div class="account-options-content">
						<p class="empty-list">Sorry! Your wishlist seems empty.</p>
						<p class="empty-list">Add products to your wishlist to see more crowd here.</p>
					</div>
					{% endif %}
			</div>

			

		</div>

	</div>
</div>

{% endblock content %}