chooseright/urls.py
"""chooseright URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views
from users import views as users_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('account/', include('users.urls', namespace='users')),
    path('tellme/', include("tellme.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

core/urls.py
from django.urls import path
from django.urls import reverse
from . import views as core_views

app_name = 'core'

urlpatterns = [
	path('base', core_views.base_view, name='base'),
	path('', core_views.home_view, name='home'),
	path('search/', core_views.search_view, name='search'),
	path('catagory/<slug:slug_text>/', core_views.catagory_view, name='catagory'),
	path('brand/<slug:slug_text>/', core_views.brand_view, name='brand'),
	path('compare/', core_views.compare_view, name='compare'),
	path('add_wishlist/<int:wished_product>/', core_views.add_to_wishlist, name='add_wishlist'),
	path('about/', core_views.about_view, name='about'),
	path('privacy_policy/', core_views.privacy_policy_view, name='privacy_policy'),
	path('terms_of_use/', core_views.terms_of_use_view, name='terms_of_use'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import reverse
from . import views as user_view

app_name = 'users'

urlpatterns = [

    path('register/', user_view.register_view, name="register"),

    path('login/',
    	user_view.LoginView.as_view(redirect_authenticated_user = True),
    	name='login'),

    path('logout/', user_view.logout_view, name="logout"),

    path('password_reset/',
    	user_view.PasswordResetView.as_view(),
    	name='password_reset'),

    path('password_reset/done/',
    	user_view.PasswordResetDoneView.as_view(),
    	name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>',
    	user_view.PasswordResetConfirmView.as_view(),
    	name='password_reset_confirm'),

    path('password_reset_complete/',
    	user_view.PasswordResetCompleteView.as_view(),
    	name='password_reset_complete'),

    path('dash_board/', user_view.dash_board_view, name="dash_board"),
    path('wish_list/', user_view.wish_list_view, name="wish_list"),
    path('feedback/', user_view.feedback_view, name="feedback"),
    path('change_password/', user_view.change_password_view, name="change_password"),
    path('profile_update/', user_view.profile_view, name="profile"),

]

templates/chooseright/about.html
{% extends 'chooseright/base.html' %}
{% block content %}

<div class="page-content">

	<h2 class="main-title"> Who We Are</h2>
	<p>Choose Right is the product of our work for fulfiling the final year project. We are a team of three members. We have worked on this project to make price comparison and shopping experiences easy for you – on a budget!, need a smart phone or a laptop. Yes we have got that covered for you. </p>
	<p>This project is about three things; high-quality products, great savings and easy shopping!</p>
	<p>We understand how the Pakistani economy and culture encourages you to go an extra mile in order to save money with every purchase. We just make it easier for you to do so!</p>
	<p>Chooseright is your highway to effortless price comparison in the Pakistani market.</p>
	<p>We’ve listed some of popular and not-so-popular merchants in Pakistan who sell similar high-quality products. So you don’t need to surf through different stores in the scorching heat (or in the super-chilled winters) to find out which one offers the best deal; we get you a list of merchants who sell the services/products you need, and the prices they charge.</p>

</div>

{% endblock %}

templates/chooseright/breadcrumbs.html
{% extends 'chooseright/base.html' %}

{% block}
<div class="Breadcrumb-wrapper">
	<ul class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Home</a>
		</li>
		<li class="breadcrumb-item">
			<a href="#">Bome</a>
		</li>
	</ul>
</div>

templates/chooseright/compare.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div class="item-detail-wraper">

	<div class="item-image-wraper">

		<img alt="Product Image" src="{% for i in query %}{% if i.product_price == com_list.min_price %}{{i.image.url}}{% endif %}{% endfor %}">
	</div>

	<div class="item-information-wraper">

		<div class="item-tittle">
			<span>Name:</span>
			{% for i in query %}
				{% if com_list.min_price == i.product_price %}{{i.product_name}}{% endif %}
			{% endfor %}
		</div>

		<div class="item-brand">
			<span>Brand:</span>
			{% for i in query %}
				{% if com_list.min_price == i.product_price %}{{i.product_brand}}{% endif %}
			{% endfor %}
		</div>

		<div class="item-price">
			<span>Price:</span>
			{{com_list.min_price}}
		</div>

		<div class="item-reviews">
			<span>Reviews:</span>
			{% for i in query %}
				{% if com_list.min_price == i.product_price %}{{i.product_review}}{% endif %}
			{% endfor %}
		</div>

		<div class="item-user-action">
			{% if current_list %}
			{% for i in query %}
				{% if com_list.min_price == i.product_price %}
					<div class="wishlist-option">
						<i class="fas fa-heart-broken"></i>
						<a href="{% url 'core:add_wishlist' wished_product=i.product_id %}?p_name={{i.product_name}}&wishlist=remove">Remove from Wishlist</a>
					</div>
				{% endif %}
			{% endfor %}
			{% else %}
				<div class="wishlist-option">
					<i class="far fa-heart"></i>
					<a href="
						{% for i in query %}
						{% if com_list.min_price == i.product_price %}
						{% url 'core:add_wishlist' wished_product=i.product_id %}?p_name={{i.product_name}}
						{% endif %}
						{% endfor %}">
						Add to Wishlist
					</a>
				</div>
			{% endif %}

		</div>
		<div class="social-share">
			<div class="fb-share">
				<i class="fab fa-facebook-f"></i>
				<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
					Share on Facebook
				</a>
			</div>
			<div class="twitter-share">
				<i class="fab fa-twitter"></i>
				<a href="https://twitter.com/home?status={{share_string}}%20{{ request.build_absolute_uri }}">
					Share on Twitter
				</a>
			</div>
		</div>			

	</div>


</div>

<div class="compare1">
	{% include 'chooseright/comparisondetails.html' %}
	<div class="sidebar-menu-wraper">

		<div class="sidebar-menu-heading">
			<h2>Popular Brands</h2>
			<hr>
		</div>

		<div class="sidebar-menu-body">

			<ul class="sidebar-menu">

				{% for brands in brand %}
					<li>
						<a href="{% url 'core:brand' slug_text=brands.slug %}">{{brands.name}}</a>
					</li>
				{% endfor %}

			</ul>

		</div>
	</div>
</div>
{% include 'chooseright/specification.html' %}

{% endblock content %}

templates/chooseright/footer.html
<div class="footer-wrapper">
			
			<div class="footer-wrapper-info">
				
				<div class="footer-col">
					<div class="footer-column-title">Register to stay updated</div>
						<div>
							<a href="{% url 'users:register' %}" class="footer-btn">Register</a>
						</div>
						<p>Register today to get latest news straight to your inbox.</p>
				</div>
				
				<div class="footer-col">
					<div class="footer-column-title">Information</div>
						<ul class="footer-list">
							<li><a href="{% url 'core:about' %}">About Us</a></li>
							<li><a href="{% url 'core:terms_of_use' %}">Terms Of Use</a></li>
							<li><a href="{% url 'core:privacy_policy' %}">Privacy Policy</a></li>
						</ul>
				</div>
				
				<div class="footer-col">
					<div class="footer-column-title">Administration</div>
						<ul class="footer-list">
							<li><a href="{% url 'admin:login' %}">Administration Site</a></li>
						</ul>
				</div>
				
			</div>

			<div class="footer-wrapper-copywrite">
				 <div align="center"><p>Copyright © 2020 Chooseright.pk. All Rights Reserved.</p></div>
			</div>
		
		</div>

templates/chooseright/header.html
<div class="header-wrapper">

	<div class="header-center">

		<div class="nav-menu-dropdown">
			{% include "chooseright/navbar_dropdown.html" %}
		</div>

		<div class="logo-left">
			<a href="{% url 'core:home' %}">
				<image class="logo" src="/static/chooseright/media/Logo.png" alt="Choose Right Logo" width="" height="100">
				</image>
			</a>
		</div>

		<div class="search-box-container">
			<form action="{% url 'core:search' %}" method="GET" value="{{request.GET.q}}">
				<input type="text" id="search" name="q" value="{{request.GET.q}}" placeholder="Search for products to compare" required>
				<button class="search-button" type="submit" value="submit">
					<i class="fas fa-search">
					</i>
				</button>	
			</form>
		</div>

		<div class="settings">
			<ul class="setting-options">
				<li id="search-mobile" class="search-icon">
					<i class="fas fa-search fa-2x"></i>
				</li>
				{% if user.is_authenticated %}

					<li class="user-profile">
						<span class="profile-menu">
							<img class="profile-image" src="{{ user.profile.image.url  }}" alt="user">
							<button id="user-profile-dropdown-btn" type="button">
								{% if user.first_name %}
									{{user.first_name}}
								{% else %}
									{{user.username}}
								{% endif %}
								<span>
								<i class="fas fa-caret-down"></i>
								</span>
							</button>
							
						</span>
					</li>

					<div id="user-profile-menu-options" class="un-active-menu">
						<ul class="user-dropdown-menu">
							<li>
								<span>
									<i class="fas fa-user-circle"></i>
									<a href="{% url 'users:dash_board' %}">My Account</a>
								</span>
							</li>
							<li>
								<span>
									<i class="far fa-heart"></i>
									<a href="{% url 'users:wish_list' %}">Wishlist</a>
								</span>
							</li>	
							<li><hr></li>
							<li>
								<span>
									<i class="fas fa-sign-out-alt"></i>
									<a href="{% url 'users:logout' %}?next={% firstof request.get_full_path '/' %}">Log Out</a>
								</span>
							</li>	
						</ul>
					</div>

				{% else %}
					<li class="sign-in">
						<a href="{% url 'users:login' %}?next={% firstof request.get_full_path '/' %}">Log In</a>
					</li>
					<li class="sign-up">
						<a id="btn-sign-up" href="{% url 'users:register' %}">Register</a>
					</li>	
				{% endif %}
			</ul>
		</div>

	</div>

</div>

templates/chooseright/home.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div class="product-row">

	{% for products in product_pages %}

			<div class="card-container">

			<div class="card-inside">
				<img class="card-img-top" src="{% for i in product %}{% if products.product_name == i.product_name %}{{i.image.url}}{% endif %}{% endfor %}" alt="Card image cap">
				<div class="card-body">
					
					<a class="card-title" href="{% url 'core:compare' %}?p_name={% for i in product %}{% if products.product_name == i.product_name %}{{i.product_name}}{% endif %}{% endfor %}">
						{% for i in product %}
							{% if products.product_name == i.product_name %}
								{{i.product_name}}
							{% endif %}
						{% endfor %}
					</a>

					<div class="card-price">
						<span class="price-sign">Rs.</span>
						<span class="price">
							{% for i in product %}
								{% if products.product_name == i.product_name %}
									{{i.product_price}}
								{% endif %}
							{% endfor %}
						</span>
					</div>
				</div>
			</div>

			<div class="card-compare">
				<a href="{% url 'core:compare' %}?p_name={% for i in product %}{% if products.product_name == i.product_name %}{{i.product_name}}{% endif %}{% endfor %}" class="compare-button"><span>Let's Compare</span></a>
			</div>

		</div>	

	{% endfor %}

</div>

{% endblock content %}

templates/chooseright/itemcard.html
<div class="product-row">

	{% for products in product_pages %}

			<div class="card-container">

				<div class="card-inside">
					<img class="card-img-top" src="/static/media/Logo.png" alt="Card image cap">
					<div class="card-body">
						<a class="card-title" href="{% url 'core:compare' %}">{{products.product_name}}</a>
						<div class="card-price">
							<span class="price-sign">Rs.</span>
							<span class="price">
								{{products.product_price}}
							</span>
						</div>
					</div>
				</div>

				<div class="card-compare">
					<a href="{% url 'core:compare' %}?p_name={% for i in product %}{% if products.product_name == i.product_name %}{{i.product_name}}{% endif %}{% endfor %}" class="compare-button"><span>Let's Compare</span></a>
				</div>

			</div>	

	{% endfor %}

</div>

templates/chooseright/navbar.html
<div class="Navigation-wrapper" role="navigation">

	<div class="Navigation-tablist" role="tablist">
		<ul class="navigation-menu">
			<li class="navigation-menu-items"><a class="home" href="{% url 'core:home' %}" role="tab"><div>Home</div></a>
			</li>
			<li class="navigation-menu-items"><a class="wishlist" href="{% url 'users:wish_list' %}" role="tab"><div>Wishlist</div></a>
			</li>
			<li class="navigation-menu-items"><a class="catagories" href="#" role="tab">
				<div>Categories</div></a>
				<ul class="sub-catagories">
					{% for catagories in catagory %}
						<li class="sub-catagories-items">
							<a href="{% url 'core:catagory' slug_text=catagories.slug %}">{{catagories.name}}</a>
						</li>
					{% endfor %}
				</ul>
				
			</li>
		</ul>
	</div>
</div>

templates/chooseright/navbar_dropdown.html
<div id="nav-menu-dropdown-btn-toggle" class="nav-menu-dropdown-btn">
	<div class="nav-menu-dropdown-btn_burger"></div>
</div>

<div id="nav-menu-dropdown-toggle" class="nav-menu-dropdown-overlay">

	<ul id="nav-list" class="nav-menu-dropdown-nav-list">

		<li class="nav-menu-item">
			<i class="fas fa-home"></i>
			<a href="{% url 'core:home' %}">Home</a>
		</li>

		<li class="nav-menu-item">
			<i class="far fa-heart"></i>
			<a href="{% url 'users:wish_list' %}">Wish List</a>
		</li>

		<li class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span><i class="fa fa-list" aria-hidden="true"></i><span>
				<span>Catagories</span>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				{% for catagories in catagory %}
				<a class="dropdown-item" href="{% url 'core:catagory' slug_text=catagories.slug %}">{{catagories.name}}</a>
				{% endfor %}
			</div>
		</li>

		{% comment %}
		<li class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span><i class="fas fa-store"></i><span>
				<span>Stores</span>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				{% for stores in store %}
				<a class="dropdown-item" href="{% url 'core:store' slug_text=stores.slug %}">{{stores.name}}</a>
				{% endfor %}
			</div>
		</li>
		{% endcomment %}


		<li class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span><i class="fas fa-tag"></i><span>
				<span>Brands</span>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					{% for brands in brand %}
					<a class="dropdown-item" href="{% url 'core:brand' slug_text=brands.slug %}">{{brands.name}}</a>
					{% endfor %}
			</div>
		</li>

	</ul>
</div>

templates/chooseright/pagination.html
{% if product_pages.has_other_pages %}


<div class="pagination">

	{% if product_pages.has_previous %}

		<a class="pagination-action" href="?page=1{% if query %}&q={{query}}{% endif %}{% if min and max %}&mini={{min}}&max={{max}}{% endif %}{% if price %}&price={{price}}{% endif %}">
			<i class="fas fa-angle-double-left"></i>
		</a>
		<a class="pagination-action" href="?page={{product_pages.previous_page_number}}{% if query %}&q={{query}}{% endif %}{% if min and max %}&mini={{min}}&max={{max}}{% endif %}{% if price %}&price={{price}}{% endif %}">
			<i class="fas fa-angle-left"></i>
		</a>

	{% endif %}

	{% for num in product_pages.paginator.page_range %}

		{% if product_pages.number == num %}
			
			<span class="pagination-number pagination-current">
				{{ num }}
			</span>

		{% elif num > product_pages.number|add:'-3' and num < product_pages.number|add:'3' %}

			<a class="pagination-number" href="?page={{num}}{% if query %}&q={{query}}{% endif %}{% if min and max %}&mini={{min}}&max={{max}}{% endif %}{% if price %}&price={{price}}{% endif %}">
				{{ num }}
			</a>

		{% endif %}

	{% endfor%}

	{% if product_pages.has_next %}

		<a class="pagination-action" href="?page={{product_pages.next_page_number}}{% if query %}&q={{query}}{% endif %}{% if min and max %}&mini={{min}}&max={{max}}{% endif %}{% if price %}&price={{price}}{% endif %}">
			<i class="fas fa-angle-right"></i>
		</a>
		<a class="pagination-action" href="?page={{product_pages.paginator.num_pages}}{% if query %}&q={{query}}{% endif %}{% if min and max %}&mini={{min}}&max={{max}}{% endif %}{% if price %}&price={{price}}{% endif %}">
			<i class="fas fa-angle-double-right"></i>
		</a>

	{% endif %}

</div>

{% endif %}

templates/chooseright/results_page.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div class="content-holder">


	<div class="side-bar-menu-wrapper">

		<div class="widget">

			<div id="product-brand-widget" class="sidebar-widget">

				<h2>Brands</h2>
				<hr>

				<ul class="widget-list">

					{% for brands in brand %}
					<li class="">
						<a class="widget-link" href="{% url 'core:brand' slug_text=brands.slug %}">
							<span>{{brands.name}}</span>
						</a>
					</li>
					{% endfor %}

				</ul>

			</div>

		</div>

		{% comment %}
		<div class="widget">

			<div id="product-store-widget" class="sidebar-widget">

				<h2>Stores</h2>
				<hr>

				<ul class="widget-list">

					{% for stores in store %}
					<li class="">
						<a class="widget-link" href="{% url 'core:store' slug_text=stores.slug %}">
							<span>{{stores.store_name}}</span>
						</a>
					</li>
					{% endfor %}
				</ul>

			</div>

		</div>
		{% endcomment %}

		<div class="widget">

			<div id="product-budget-widget">

				<h2>Specify Your Budget</h2>
				<hr>

				<div class="product-budget-selection">

					<form class="price-filter-wrapper" action="{{ request.path }}">
						<div class="price-input-wrapper">
							<input id="mini-value" class="price-input" type="number" name="mini-value" placeholder="Min." required="">
							<span class="price-input-sign">Rs.</span>
						</div>

						<span class="price-filter-span">to</span>

						<div class="price-input-wrapper">
							<input id="max-value" class="price-input" type="number" name="max-value" placeholder="Max." required="">
							<span class="price-input-sign">Rs.</span>
						</div>
						<br/>
						<button class="price-filter-apply" type="button" onclick="getInputValue('{{ request.path }}');">Apply</button>
					</form>

				</div>

			</div>

		</div>

	</div>

	<div class="search-results-container">

		<div class="search-result-bar">
			<div class="search-result-bar-left">
				<h1>Results for 
					<span>{{slug}} {{tag}}</span>
				</h1>
			</div>

			<div class="search-result-bar-right">
				<span class="filter">
					<i class="fas fa-funnel-dollar"></i>
					Filter
				</span>
				<span class="sort-txt">Sort By: </span>
				<span class="sort-select">
					<select name="sortby" id="sortby">
						<option value="" selected>Sort By</option>
						<option value="{{ request.path  }}?&price=asc">
							Price Low To High
						</option>
						<option value="{{ request.path  }}?&price=desc">
							Price High To Low
						</option>
					</select>


				</span>
			</div>
		</div>

		{% if product_pages %}

			<div class="product-row">

				{% for products in product_pages %}

				<div class="card-container">

					<div class="card-inside">
						<img class="card-img-top" src="{% for i in product %}{% if products.product_id == i.product_id %}{{i.image.url}}{% endif %}{% endfor %}" alt="Card image cap">
						<div class="card-body">
							
							<a class="card-title" href="{% url 'core:compare' %}?p_name={{products.product_name}}">
								{% for i in product %}
								{% if products.product_id == i.product_id %}
								{{i.product_name}}
								{% endif %}
								{% endfor %}
							</a>

							<div class="card-price">
								<span class="price-sign">Rs.</span>
								<span class="price">
									{% for i in product %}
									{% if products.product_id == i.product_id %}
									{{i.product_price}}
									{% endif %}
									{% endfor %}
								</span>
							</div>
						</div>
					</div>

					<div class="card-compare">
						<a href="{% url 'core:compare' %}?p_name={{products.product_name}}" class="compare-button"><span>Let's Compare</span></a>
					</div>

				</div>	

				{% endfor %}

			</div>

			{% else %}
				<div class="content-empty">
					<p class="empty-list">
						<strong>Sorry we didn't find any relevant match for your querry.</strong>
						<br><br>
						To proceed, you can perform one of the following actions:
						<br>
						- Review your search term for spelling or typing mistakes
						<br>
						- You can review you search term to be more specific to the product, try more general keywords
						<br>
						- Include exact product name in search term if you have it
						<br>
						- Reset the filter and try again.
					</p>
				</div>
			{% endif %}
		
		
	</div>

</div>


{% endblock %}

templates/chooseright/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'chooseright/js/jquery.js' %}"></script>

{# My Javascript file for site #}
<script type="text/javascript" src="{% static 'chooseright/js/main.js' %}"></script>

{# Javascript files for Bootstrap #}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/chooseright/searchresults.html
{% extends 'chooseright/base.html' %}

{% block content %}

<div class="content-holder">


	<div class="side-bar-menu-wrapper">

		<div class="widget">

			<div id="product-brand-widget" class="sidebar-widget">

				<h2>Brands</h2>
				<hr>

				<ul class="widget-list">

					{% for brands in brand %}
					<li class="">
						<a class="widget-link" href="{% url 'core:brand' slug_text=brands.slug %}">
							<span>{{brands.name}}</span>
						</a>
					</li>
					{% endfor %}

				</ul>

			</div>

		</div>


		{% comment %}
		<div class="widget">

			<div id="product-store-widget" class="sidebar-widget">

				<h2>Stores</h2>
				<hr>

				<ul class="widget-list">

					{% for stores in store %}
					<li class="">
						<a class="widget-link" href="">
							<span>{{stores.store_name}}</span>
						</a>
					</li>
					{% endfor %}
				</ul>

			</div>

		</div>
		{% endcomment %}

		<div class="widget">

			<div id="product-budget-widget">

				<h2>Specify Your Budget</h2>
				<hr>

				<div class="product-budget-selection">

					<form class="price-filter-wrapper" action="{{ request.path }}">
						<div class="price-input-wrapper">
							<input id="mini-value" class="price-input" type="number" name="mini-value" placeholder="Min." required="">
							<span class="price-input-sign">Rs.</span>
						</div>

						<span class="price-filter-span">to</span>

						<div class="price-input-wrapper">
							<input id="max-value" class="price-input" type="number" name="max-value" placeholder="Max." required="">
							<span class="price-input-sign">Rs.</span>
						</div>
						<br/>
						<button class="price-filter-apply" type="button" onclick="getSearchQuery('{{ request.get_full_path }}');">Apply</button>
					</form>

				</div>

			</div>

		</div>

	</div>

	<div class="search-results-container">

		<div class="search-result-bar">
			<div class="search-result-bar-left">
				<h1>Search Results for 
					<span>{{query}}</span>
				</h1>
			</div>

			<div class="search-result-bar-right">
				<span class="filter">
					<i class="fas fa-funnel-dollar"></i>
					Filter
				</span>
				<span class="sort-txt">Sort By: </span>
				<span class="sort-select">
					<select name="sortby" id="sortby">
						<option value="" selected>Sort By</option>
						<option value="{% url 'core:search' %}?q={{query}}&price=asc"> Price Low To High </option>
						<option value="{% url 'core:search' %}?q={{query}}&price=desc"> Price High To Low </option>
					</select>
				</span>
			</div>
		</div>

		{% if request.GET.q != "" %}

			{% if results %}

				<div class="product-row">

					{% for products in product_pages %}

					<div class="card-container">

						<div class="card-inside">
							<img class="card-img-top" src="{% for i in results %}{% if products.product_id == i.product_id %}{{i.image.url}}{% endif %}{% endfor %}" alt="Product Image">
							<div class="card-body">
								<a class="card-title" href="{% url 'core:compare' %}?p_name={{products.product_name}}">{{products.product_name}}</a>
								<div class="card-price">
									<span class="price-sign">Rs.</span>
									<span class="price">
										{{products.product_price}}
									</span>
								</div>
							</div>
						</div>

						<div class="card-compare">
							<a href="{% url 'core:compare' %}?p_name={{products.product_name}}" class="compare-button"><span>Let's Compare</span></a>
						</div>

					</div>	

					{% endfor %}

				</div>

			{% else %}
				<div class="content-empty">
					<p class="empty-list">
						<strong>Sorry we didn't find any relevant match for your search: {{request.GET.q}}</strong>
						<br><br>
						To proceed, you can perform one of the following actions:
						<br>
						- Review your search term for spelling or typing mistakes.
						<br>
						- You can review you search term to be more specific to the product, try more general keywords.
						<br>
						- Include exact product name in search term if you have it.
						<br>
						- The product you are lokking for might not be available right now. Search for any other product.
					</p>
				</div>
			{% endif %}

		{% endif %}

	</div>

</div>


{% endblock %}